# Generated by Django 6.0.3 on 2026-05-25 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('road', 'Road Damage and Potholes'), ('garbage', 'Garbage and Waste'), ('water', 'Water Supply/Leakage'), ('electricity', 'Street Lighting'), ('drainage', 'Drainage/Sewage'), ('encroachment', 'Encroachment'), ('traffic', 'Traffic & Parking'), ('noise', 'Noise Pollution'), ('air', 'Air Pollution'), ('safety', 'Public Safety Hazard'), ('animals', 'Stray Animals'), ('other', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Adopted', 'Adopted (In Progress)'), ('Pending Verification', 'Pending Verification'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_help_requested', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_violations', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='violations.violation')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('points_awarded_reporter', models.IntegerField(default=10)),
                ('points_awarded_worker', models.IntegerField(default=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_certificates', to=settings.AUTH_USER_MODEL)),
                ('issued_to_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_certificates', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='violations.violation')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='submissions/before/')),
                ('work_description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='violations.violation')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submissions/after/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_photos', to='violations.worksubmission')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='violations.worksubmission')),
            ],
            options={
                'unique_together': {('submission', 'user')},
            },
        ),
    ]
