# Generated by Django 6.0.3 on 2026-09-13 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(('reported_by', models.F('adopted_by')), _negated=True), name='prevent_self_adoption'),
        ),
    ]
